apiVersion: 1

contactPoints:
  - orgId: 1
    name: ids-email-alerts
    receivers:
      - uid: ids-email-receiver
        type: email
        settings:
          addresses: "dheerajpaniharam@gmail.com"
          message: "{{ template \"ids-email-template\" . }}"
        disableResolveMessage: false
